### ISSUE TITLE
可否将luaecs.c拆分为多个文件

### ISSUE THREAD

**Issue by dpull** [cloudwu/luaecs#16]
luaecs.c 目前是多个功能的一个合集，建议进行拆分下。

1. code review变得清晰，目前3000多行代码，不容易看
2. 进行一些库操作的抽象，然后方便写单元测试去验证（我之前也提过几个缓存导致的bug）

**Comment by cloudwu** [comment]
https://github.com/cloudwu/luaecs/commit/5d7e846989cb686f75db58a62da11a432a80183b
