### ISSUE TITLE
关于group_enable api 重置上一次group_enable数据问题

### ISSUE THREAD

**Issue by zhengtg** [cloudwu/luaecs#24]
在测试test15.lua代码时发现一个问题：
w:group_enable("visible", 0,2),之后，再调用w:group_enable("visible", 1000,1001)，则第二次调用时，会把group 0，和group 2中entity 的visible 组件进行disable，最终只enable group 1000和1001，该api的设计逻辑就是这样还是bug？
按现有的逻辑，查看了group_enable c代码实现，当group_enable的group id超过MAXGROUP（1024）之后，就会以1024个group循环进行enable，这导致了，当group_enable传入的groupid超过1024后，只会enable 总数对1024取模后的group,这个结果是不符合api的预期，应该是个bug。

另外，从应用上考虑，是否新增一个group_disable的api？

简单修改test15.lua即可复现该问题。

**Comment by cloudwu** [comment]
这是一个特性。

因为这个特性，我觉得不需要 group_disable ，因为你只需要自己管理 group id 集合即可。比如用九宫格管理可见对象，只需要维护一个 9 的 group id 集合，当集合变化的时候就 enable 一次这个集合。

单个 tag 的 enable/disable 操作并不是稳定的，现在这样批量 enable 因为是一次写入，好过不断的改写。

**Comment by zhengtg** [comment]
嗯，看了commit，保持这个特性，对于管理全局唯一的情况比较友好。但如果某个场景下需要取消所有选择时，没有disable比较不方便，采用维护一个空的group？

**Comment by cloudwu** [comment]
取消你可以直接 clear 整个 tag 啊，不需要调用 enable 。
