### ISSUE TITLE
关于LuaECS使用中的一些请教

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/luaecs#26]
因为之前对 ECS 这种模式不熟悉，所以现在尝试以最简单的，MUD 这种形式的游戏来尝试一下这个模式。
遇到一些比较迷惑和带有一定犹豫的问题。
在 Area，也就是场景服务的设计中我是这样做的：

1. 我将房间只是相当于一个坐标，当然会为房间构造一个实体。
2. 玩家、物品、NPC 都会拥有归属，权且将这个归属叫做 parent，这三类在场景服务内的 parent 会是房间的 entity id。
3. Skynet 框架不会处理消息，它只会在收到 Agent 的消息的时候将消息放到 world 内。
4. 服务每帧的回调负责驱动各个系统来处理消息。

我的疑问在于：

1. 当我想要获取到某个玩家所处的房间内的所有实体时，如果采用上述第二种方式实现，需要进行遍历才能获取到。但我看到 group API 后，我想完全可以将这些同属一个房间的实体都打上 GROUP，就以房间的 entity 作为  groupid 这样的会就会非常容易实现。但在切换房间的时候，group 并没有移除 eid 的这种操作。关于这点我想问的是，会提供基于 group 操作的其他 API 么。
2. 第二个问题是，在处理收到消息的系统中，我必然会根据消息从 World 中去获取信息、修改单个的 Entity（我看到近期新增的：access、fetch、submit、readall API 给了我这样的可能）。。这样的使用方式是不是并不是 ECS 推荐的形式，因为我隐约觉得这种搞法，就和通常的做法差不多了。

一个实际的例子：
客户端会发出 move 来移动到其他房间 look 来查看房间内的指令。在收到消息的时候，会将这些信息构造一个实体，挂上 message 组件放到 World中。在处理信息的系统中，我有两种可能的办法来建立这个系统。

我可以在 遍历消息时，遇到 move 指令，将修改判断是否能够移动，修改实体的 parentid，再将新房间的信息返回给客户端去。

但我还可以用另外一种方式：

遇到 move 指令时，查找对应的实体并打上 movement 标签，表示需要有消息进行处理，然后给实体挂上一个 message 组件，这个组件存储消息的内容。
MovementSystem 遍历有 movement 标签的组件，然后在遍历过程中做对应的操作。操作完毕给实体打上 look 标签。
LookSystem 遍历有 look 标签的实体，然后获取实体当前房间信息，返回给客户端。

哪一种方式更为推荐。

**Comment by zhengtg** [comment]
问题1: 按group的设计，不是在这个场景下用的，可以参考 #24 ，不过，你可以用一个lua组件维护这个数据，功能和group一样就行了
问题2: 在大部分的业务场下，个人更倾向于在input system中，直接把消息处理了。有严格顺序或者特殊要求的，将input数据放到相关业务系统中再处理
