### ISSUE TITLE
template_instance 是否需要支持一下覆写默认数据

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/luaecs#28]
我看了一下，对于一个 template ，在 instance 的时候，是不可以在最后一个参数内包括模板内已经包含的组件的数据。

这样似乎感觉有点不够人性化。

**Comment by cloudwu** [comment]
这个接口我设计成给更高层框架代码使用，用于持久化，而不是业务直接调用的。
它要求的是严格的语义，而不是弹性。
