### ISSUE TITLE
是否支持lua5.4版本？

### ISSUE THREAD

**Issue by Queen-Studio** [cloudwu/luaecs#32]
使用VS2019编译为lua5.4.7版本的库，使用README.md中第1个例子进行测试，似乎存在着问题。不知道这个库兼容哪些lua版本。
出错信息如下：
lua: ./lualibs/ecs.lua:406: Invalid .x type nil (float)
stack traceback:
        [C]: in upvalue 'cobject_check'
        ./lualibs/ecs.lua:406: in upvalue '_new_entity'
        ./lualibs/ecs.lua:435: in method 'new'
        ./test/luaecs/basic.lua:21: in main chunk
        [C]: in function 'dofile'
        test.lua:234: in main chunk
        [C]: in ?

basic.lua
`-- Create a world
local ecs = require("ecs")
local w = ecs.world()

-- Register a new type "vector( x:float, y:float )" into world.
-- It's a C component (The data is in C memory).
w:register {
	name = "vector",
	"x:float",
	"y:float",
}

-- Register a new type "name" into world.
-- It's a Lua component (The value can be any lua object)
w:register {
	name = "name",
	type = "lua",
}

-- Create a new entity with components vector and name.
local eid = w:new {
	vector = { 1.0, 2.0 },
	name = "point",
}

-- Iterate every entity with component vector and name
for v in w:select "vector:in name:in" do
	-- v is the iterator, we can read compionent from it.
	-- DO NOT store v outside of the iteration
	print(v.name)	-- output : point
	print(v.vector.x, v.vector.y)	-- output: 1.0, 2.0
end`

**Comment by cloudwu** [comment]
readme 写错了，已改过来。测试以 test*.lua 为准。
