### ISSUE TITLE
请问，不暴露 Entity ID 的想法是什么。

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/luaecs#5]
当我不想在 System 中修改数据的话，我想要修改某个 Entity 的数据，那是不是就没有选择，只能遍历一次来获取目标 Entity。

还是，您的思路，是在 System 处理的时候，需要修改的话就直接修改了。

举个简单例子：
一个场景，玩家进入，我们需要把玩家信息添加到成 Entity。

那玩家离开了，我得把它 remove 掉。

**Comment by cloudwu** [comment]
因为，限制相互引用可以让实现更简单高效。迫使你寻找新的方法来配合这种用法，这样就可以让 system 间尽量解耦，减少出 bug 的概率。

本质上是，检索特定的 entity 变成了 O(n) 而不是 O(1) 的时间复杂度。如果你用某种排序 id ，也可以降低到 O(log N) 。

通常你可以把代做的事情记录下来，打上 tag ，然后用独立的 system 再针对 tag 批量做。针对这种模式，还提供了一种叫 order  tag 的东西，可以控制 select 的次序。也就是说，你可以控制这个 tag 下的 entity 哪个先返回，哪个后返回。https://github.com/cloudwu/luaecs/blob/master/test11.lua

当你在处理一个 order tag 对应的 entity 时，如果发现当前还不足以做处理，可以把 tag 设置为 false ，那么 select 迭代器之后还会再把这个 entity 返回一次；下次 select 的过程，将保持上一次最终的次序。

少数场合一定要用 entity 的引用，这里提供了一个弱引用方案：https://github.com/cloudwu/luaecs/blob/master/test12.lua
你可以在new entity  的时候传入 reference 对象：你自己给的空 table 。之后可以用 sync 把 entity 同步到这个 table 中。

**Comment by cloudwu** [comment]
另外，这更接近数据库的接口语义。你无法一直持有一个数据库中指定项目的引用，并随时修改它。你只能把更新请求提交给数据库，同时告诉数据库索引的条件：例如 id  是多少。而数据库的实现并不保证你从 id 找到对象一定是 O(1) 的。

如果暴露 entity id ，无非是假定了通过它能够以 O(1) 的方式检索到，除此之外， entity id 就是一个普通的 component 而已。

**Comment by Gowa2017** [comment]
感谢 理解了

**Comment by Gowa2017** [comment]
非常感谢

云风 ***@***.***> 于 2022年1月26日周三 14:02写道：

**Comment by cloudwu** [comment]
不出意外，我会用新增加的 index cache 代替之前的 reference 方案：https://github.com/cloudwu/luaecs/blob/master/test13.lua

即用一个额外的数据结构对某个 key 做索引，可以在后面快速创建迭代器供 sync 使用。

**Comment by cloudwu** [comment]
https://blog.codingnow.com/2022/02/ecs_entity_reference.html

**Comment by Gowa2017** [comment]
为何不考虑一下直接暴露组件池的索引出来。这样不是更直接么。这样也只须一个 id 组件即可了。

**Comment by cloudwu** [comment]
那个 id 只有 32bit, 它会变的。

**Comment by Gowa2017** [comment]
> 不出意外，我会用新增加的 index cache 代替之前的 reference 方案：https://github.com/cloudwu/luaecs/blob/master/test13.lua
> 
> 即用一个额外的数据结构对某个 key 做索引，可以在后面快速创建迭代器供 sync 使用。

默认的缓存大小是1024，是否小了一点。或是刻意设计这样的行为，让使用的时候不要依赖于 index_cache 的那个长久引用。
1024 很容易就哈希碰撞了。

**Comment by cloudwu** [comment]
大小是可以设置的。

我也不认为 1024 小。因为这是 cache ，记录的不是所有你的引用，而是 **最近使用** 的引用。不应该在同时使用大量的引用，那一般会有用 select 批量解决的方案。比如场景树记录父节点这种。应该找到方案用 O(n) 的遍历去解开 m 个引用的问题。

**Comment by Gowa2017** [comment]
确实 解引用是一个非常慢的行为。不可当成常规手段使用。
