### ISSUE TITLE
我知道可以动态添加component 那如何卸掉

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/luaecs#6]
如题。

**Comment by cloudwu** [comment]
只能 clear 整个类型的所有 component 或删除整个 entity (然后重建）。

tag 可以单独 disable 。

**Comment by Gowa2017** [comment]
> 只能 clear 整个类型的所有 component 或删除整个 entity (然后重建）。
> 
> tag 可以单独 disable 。

感谢。
