### ISSUE TITLE
关于拥有多个Entity 间的关联。

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/luaecs#7]
比如，在场景中，需要管理玩家，或 NPC，这些都作为 Entity。
它们身上会有装备、物品等东西。

我可以用一个 Inventory，一个 Equipable 组件来挂在这些 Character 身上。但想要将其实际上的关联上 装备或物品，想要在 C 内存储这种管理很困难（数据库也是这样）；若我选择将这些东西放在 Lua 里面，就完全可以随意组合成 Table。

在这里的疑问就是，在选择将数据放在 C 或 Lua 的界限有没有什么建议存在？

或者用另外一种方式，装备、物品自己挂上一个组件，来表明其所属于哪个 Character。但这在进行更新或者动作的时候，就必须去查询遍历一次来进行对应的响应操作，代码也会丑陋一些（现在加了 index cache 会便宜一些了）。或者是，这种情况不得不像你在 [这篇文章](https://blog.codingnow.com/2021/11/related_components.html) 一样，在框架外部做一些工作了。

**Comment by cloudwu** [comment]
之所以有 C 结构的支持，在我们的项目中一般处于两个目的：

1. 对于大量数据的计算，是性能敏感的。我需要在 C 代码中处理大量同类的 Component 。这时， Component 存放在 C 数据中即方便，又高效。
2. 需要方便的做持久化。这时，C 数据可以直接内存块复制出来就够了。

在我们的项目中还有第三个目的，但并不普适：C 数据比 Lua 数据更紧凑，可以节省客观的内存。

除此之外，我建议尽可能的使用 Lua 原生结构。

以上，似乎没有太多把 Inventory 放在 C 数据中的需要。而 Inventory 完全可以作为用一个 Lua table 当成 Character 的一个组件。

如果 Inventory 没有和 Character 强关联的话，它只表述一个物品在角色身上，那么单独作为 Entity 也不太所谓，增加一个 Owner id 组件标识一下即可；如果有强关联，比如会给角色增加 Buff ，我觉得应该在物品进入或离开角色的 System 中做一些限制，Buff 本身还是应该记录在 Character 上的，和 Inventory 分离。

比方说你可以这样：当一个角色的物品即将增加或减少，这就意味着这个角色 Inventory 即将改变角色本身（增加/减少 Buff），这个时候，你需要一个 system 专门处理该角色的 Inventory ，在这个 system 中，它会需要遍历所有该角色的物品。你可以在这样一个 system 运行之前，用一个 system 先遍历所有的物品，并把关联的那个特定的 Character 所有的物品打上 tag ；其后，你就可以单独遍历这个 tag ，筛选出关注的物品。如果你有若干 tag 可以灵活使用，就能同时标注几个不同的 Character 。你还可以找到很多方案优化这个过程。

**Comment by Gowa2017** [comment]
非常感谢。因为某些系统的计算可能也是比较频繁所以我也想要把数据 放到 C内。但实际上发觉有些简单而不够单一的系统这样用反而会有很多不便。那么，我将在对性能敏感才将数据放在 C 内。
大多数时候，其实应该简单的 LUA 实现的 ECS 系统就够用了。
